version: '3.9'
volumes:
  user_service_db:
  game_service_db:
services:
  nginx:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  game_db:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=some_user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - game_service_db:/data/db

  user_db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=some_user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - user_service_db:/data/db

  # game_server start
  game_server:
    image: project_deflector/game_server:1.0
    network_mode: host
  # game_server end

  # realtime_server start
  realtime_server:
    image: project_deflector/realtime_server:1.0
    network_mode: host
  # realtime_server end

  # matchmaking_server start
  matchmaking_server:
    image: project_deflector/matchmaking_server:1.0
    network_mode: host
  # matchmaking_server end

  # user_server start
  user_server:
    image: project_deflector/user_server:1.0
    network_mode: host
  # user_server end
