version: '3.9'
services:
  nginx:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  # game_server start
  game_server:
    image: project_deflector/game_server:1.0
    network_mode: host
  # game_server end

  # realtime_server start
  realtime_server:
    image: project_deflector/realtime_server:1.0
    network_mode: host
  # realtime_server end

  # matchmaking_server start
  matchmaking_server:
    image: project_deflector/matchmaking_server:1.0
    network_mode: host
  # matchmaking_server end
